theme: jekyll-theme-hacker
title: Babak Ahmadi
description: A short description of my blog's purpose
url: Canonical URL for this blog
author:
  name: Babak
  email: babak at email
  url: my website

# paginate: [Number of posts in one paginated section (default: 3)]
owner: Babak Ahmadi
year: 2021
